name: skin_disease_backup
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  awesome_dialog: ^3.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
#  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  image_picker: ^1.0.7
  path: ^1.9.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sqflite: ^2.3.3+1

flutter_icon:
  android: "app_logo"
  ios: true
  image_path: "assets/app_icon/clinical-assessment.png"
  min_sdk_android: 24

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/image/
    - assets/app_icon/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/font/HelveticaNeueLight.otf
        - asset: assets/font/HelveticaNeueMedium.otf
          weight: 600
        - asset: assets/font/HelveticaNeueBold.otf
          weight: 700
        - asset: assets/font/HelveticaNeueThin.otf
          weight: 300
#      - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
